# Generated by Django 2.1.1 on 2018-10-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.CharField(default=0, max_length=3, verbose_name='年龄'),
        ),
    ]
