# Generated by Django 2.1.1 on 2018-10-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.CharField(default=18, max_length=3, verbose_name='年龄'),
        ),
    ]
